apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport-svc
spec:
  selector:
    app: nginx-multitool
  type: NodePort
  ports:
  - name: http-nginx
    port: 80
    protocol: TCP
    nodePort: 30080
  - name: http-multitool
    port: 8080
    protocol: TCP
    nodePort: 30880
    