---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox:1.37.0
        command: [ "sh", "-c", "while [ true ]; do echo \"busybox-multitool: $(date '+%Y-%m-%d %H:%M:%S')\" >> /data/busybox-multitool.txt; sleep 5; done" ]
        volumeMounts:
        - name: data-vol
          mountPath: /data
      - name: multitool
        image: wbitt/network-multitool:minimal
        command: [ "sh", "-c", "while [ true ]; do cat /data/busybox-multitool.txt; sleep 5; done" ]
        volumeMounts:
        - name: data-vol
          mountPath: /data
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: busybox-multitool-pvc
