---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfc-multitool-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "microk8s-hostpath"    # <-- добавлен
  resources:
    requests:
      storage: 1Gi