apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: netology-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]