apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: web
      port: 8384
      targetPort: 8384
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
    - name: sync
      port: 22000
      targetPort: 22000
      protocol: TCP
    - name: discovery
      port: 21027
      targetPort: 21027
      protocol: UDP